---
 - name: Generate config file
   hosts: all
   connection: local
   gather_facts: no

   tasks:

    - name: create directory
      file:
       path: "{{ config }}"
       state: directory

    - name: create config for device
      template:
       src: template/base_settings.j2
       dest: "{{ config }}/{{ inventory_hostname }}.conf"

