---
- name: GENERATE A REPORT
  hosts: all
  gather_facts: no
  connection: local

  roles:
    - ansible-network.network-engine

  tasks:
  - name: CAPTURE SHOW IP INTERFACE
    ios_command:
      provider: "{{ cred }}"
      commands:
        - show ip arp
    register: output

  - name: DISPLAY THE OUTPUT
    debug: var=output.stdout

  - name: PARSE THE RAW OUTPUT
    command_parser:
      file: "parser/show_ip_arp.yaml"
      content: "{{ output.stdout[0] }}"

  - name: DISPLAY THE DATA
    debug: var=ip_arp_facts

