---
- name: OSPF config template
  hosts: all
  gather_facts: no
  connection: network_cli
  
  tasks:

  - name: Set interface IPv4 address
    nxos_l3_interface:
     name: "{{ item.interface }}"
     ipv4: "{{ item.ip_addr }}"
    with_items: "{{ l3_interfaces }}"

  - name: Enable OSPF process
    nxos_ospf:
     ospf: "{{ ospf_process_id }}"
     state: present
   
  - name: Configure OSPF interfaces
    nxos_interface_ospf:
     interface: "{{ item.interface }}"
     ospf: "{{ ospf_process_id }}"
     area: 0
     cost: default    
    with_items: "{{ l3_interfaces }}"

  - name: unshut interfaces
    nxos_config:
     src: nxos_template.j2

 # - name: show output
 #   debug:
  #   var: output.stdout
